### ISSUE TITLE
Unable to resolve Font - Null Value Exception

### ISSUE THREAD

**Issue by hasalasri** [DarkByte7/VisualPlus#70]
I get this error when I try to open the solution. It get stuck here doesn't allow me to even close visual studio.

Message:
Value cannot be null.
Parameter name: The string is null or empty. text

Type:
System.ArgumentNullException

Stack Trace:
   at VisualPlus.Managers.FontManager.FontInstalled(String fontName)
   at VisualPlus.Structure.Theme.ResolveFontFamily(String fontName, String defaultFontName)
   at VisualPlus.Structure.Theme.Deserialize(XContainer themeContainer)

Help Link: 
Source: VisualPlus
Target Site: Boolean FontInstalled(System.String)

**Comment by DarkByte7** [comment]
You don't mention which version your using? This issue was resolved in the latest version.

If you still want to use that version you can go into your Form designer files Ex: `form1.Designer.cs` in your project and remove all the Font setters for the controls.

Example:
`this.MyVisualButton.Font = new System.Drawing.Font("Segoe UI", 8.25F);`

**Comment by hasalasri** [comment]
Thanks I removed all "this.MyVisualButton.Font = new System.Drawing.Font("Segoe UI", 8.25"
but still getting the same error. I'm using 0.4.1.4-beta. I tried different versions but the result is the same.
![image](https://user-images.githubusercontent.com/7276389/43993760-67af1438-9d47-11e8-84e4-146f34fde1d9.png)

**Comment by DarkByte7** [comment]
@hasalasri Have you tried the latest version? Link: [v0.4.1.5](https://github.com/DarkByte7/VisualPlus/releases/tag/v0.4.1.5)
